SET (ADF_BUILD_FOUND FALSE)


UNSET( RBDL_ADF_MODEL_INCLUDE_DIR              CACHE)   
UNSET( RBDL_ADF_LIBRARY                  CACHE)  

FIND_PATH (RBDL_ADF_MODEL_INCLUDE_DIR rbdl_model/BuildRBDLModel.h
HINT
~/catkin_ws/src/ambf_control_system/rbdl_model/include
)

FIND_LIBRARY (RBDL_ADF_LIBRARY rbdl_model
PATHS
~/catkin_ws/devel/lib
)

IF (RBDL_ADF_MODEL_INCLUDE_DIR AND RBDL_ADF_LIBRARY)
  SET (ADF_BUILD_FOUND TRUE)
  MESSAGE(STATUS "Found RBDLModel: ${RBDL_ADF_LIBRARY}")
ELSE(RBDL_ADF_MODEL_INCLUDE_DIR AND RBDL_ADF_LIBRARY)   
  SET (ADF_BUILD_FOUND FALSE) 
  MESSAGE (SEND_ERROR " Could not find AMBF CONTROL SYSTEM.")
ENDIF (RBDL_ADF_MODEL_INCLUDE_DIR AND RBDL_ADF_LIBRARY)

